#!/bin/bash
# ws-generate-files.sh — Generate all workspace files in one shot
# Usage: ws-generate-files.sh <workspace_path> <slot> <branch> <color> <emoji> <mode> [spec]
#
# Generates: CLAUDE.local.md, .worktree-env.sh, .vscode/settings.json (per repo),
#             .code-workspace (multi-repo), .env.local (per repo with port substitution)

set -euo pipefail
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

WS_PATH="$1"
SLOT="$2"
BRANCH="$3"
COLOR="$4"
EMOJI="$5"
MODE="${6:-worktree}"
SPEC="${7:-none}"
GOAL="${8:-}"
DATE=$(date '+%Y-%m-%d')
SLUG=$(echo "$BRANCH" | tr '/' '-')

# --- Find config ---
CONFIG=""
PROJECT_ROOT=""
for dir in "$WS_PATH" "$(git -C "$WS_PATH" rev-parse --show-toplevel 2>/dev/null || echo '')"; do
  [ -n "$dir" ] && [ -f "$dir/.claude-workspaces.json" ] && CONFIG="$dir/.claude-workspaces.json" && PROJECT_ROOT="$dir" && break
done

# Also check parent project roots from registry
if [ -z "$CONFIG" ] && [ -f "$HOME/.claude-workspaces/registry.json" ]; then
  eval "$(python3 -c "
import json, os
reg = json.load(open(os.path.expanduser('~/.claude-workspaces/registry.json')))
ws = '$WS_PATH'
for s, w in reg.get('workspaces', {}).items():
    if w.get('workspace_path') == ws:
        pr = w.get('project_root', '')
        if pr and os.path.isfile(os.path.join(pr, '.claude-workspaces.json')):
            print(f'CONFIG={os.path.join(pr, \".claude-workspaces.json\")!r}')
            print(f'PROJECT_ROOT={pr!r}')
        break
" 2>/dev/null)" 2>/dev/null || true
fi

# --- Parse config ---
if [ -n "$CONFIG" ]; then
  eval "$(python3 -c "
import json, os

config = json.load(open('$CONFIG'))
repos = config.get('repos', [])
port_step = config.get('port_step', 10)
slot = int('$SLOT')
ws_path = '$WS_PATH'
branch = '$BRANCH'
slug = '$SLUG'
color = '$COLOR'
emoji = '$EMOJI'
project_root = '$PROJECT_ROOT'

# Calculate ports
repo_info = []
for r in repos:
    port = r.get('port_base', 3000) + slot * port_step
    repo_info.append({
        'name': r['name'],
        'port': port,
        'origin': r.get('origin', '.'),
        'env_template': r.get('env_template', {})
    })

# Output as shell vars
names = ' '.join(r['name'] for r in repo_info)
ports = ' '.join(str(r['port']) for r in repo_info)
origins = '|'.join(r['origin'] for r in repo_info)
print(f'REPO_NAMES=({names})')
print(f'REPO_PORTS=({ports})')
print(f'REPO_ORIGINS=\"{origins}\"')
print(f'REPO_COUNT={len(repo_info)}')
print(f'PORT_STEP={port_step}')
" 2>/dev/null)"
fi

# Defaults if no config
REPO_COUNT=${REPO_COUNT:-0}

# --- 1. CLAUDE.local.md ---
REPOS_LIST=""
if [ "$REPO_COUNT" -gt 0 ]; then
  IFS='|' read -ra ORIGINS <<< "$REPO_ORIGINS"
  for i in $(seq 0 $((REPO_COUNT - 1))); do
    REPOS_LIST="$REPOS_LIST  - ${REPO_NAMES[$i]} -> $WS_PATH/${REPO_NAMES[$i]} (port ${REPO_PORTS[$i]})\n"
  done
fi

cat > "$WS_PATH/CLAUDE.local.md" << CLAUDEEOF
# Workspace — $BRANCH

## Workspace identity
Always prefix your first response in a conversation with the workspace badge:
$EMOJI **[w$SLOT] $BRANCH**

This helps the user know which workspace this Claude session is attached to.

## Workspace info
- **Slot**: $SLOT
- **Mode**: $MODE
- **Branch**: \`$BRANCH\`
- **Created**: $DATE
- **Repos**:
$(echo -e "$REPOS_LIST")
## Goal of this workspace
$GOAL

## Spec
$SPEC

## Notes / decisions / TODOs

CLAUDEEOF
echo "  ✓ CLAUDE.local.md"

# --- 2. .worktree-env.sh ---
cat > "$WS_PATH/.worktree-env.sh" << 'ENVEOF'
#!/bin/bash
# Auto-generated by workspace plugin — do not edit (gitignored)
ENVEOF
cat >> "$WS_PATH/.worktree-env.sh" << ENVEOF2
export WS_SLOT=$SLOT
export WS_BRANCH="$BRANCH"
export WS_COLOR="$COLOR"
export WS_EMOJI="$EMOJI"

# OSC 11: set terminal background color (WezTerm, iTerm2, Kitty)
printf '\033]11;%s\007' "\$WS_COLOR"

# OSC 1337: set tab title via WezTerm user var (survives Claude Code title resets)
TITLE="\$WS_EMOJI \$WS_BRANCH [w\$WS_SLOT]"
B64=\$(echo -n "\$TITLE" | base64)
printf '\033]1337;SetUserVar=panetitle=%s\007' "\$B64"
ENVEOF2
echo "  ✓ .worktree-env.sh"

# --- 3. .vscode/settings.json per repo (merge if exists) ---
if [ "$REPO_COUNT" -gt 0 ]; then
  for i in $(seq 0 $((REPO_COUNT - 1))); do
    REPO_DIR="$WS_PATH/${REPO_NAMES[$i]}"
    [ ! -d "$REPO_DIR" ] && continue
    VSCODE_DIR="$REPO_DIR/.vscode"
    VSCODE_FILE="$VSCODE_DIR/settings.json"
    mkdir -p "$VSCODE_DIR"

    if [ -f "$VSCODE_FILE" ]; then
      # Merge: add/replace colorCustomizations
      python3 -c "
import json
f = '$VSCODE_FILE'
try:
    settings = json.load(open(f))
except:
    settings = {}
settings['workbench.colorCustomizations'] = {
    'titleBar.activeBackground': '$COLOR',
    'titleBar.activeForeground': '#ffffff',
    'statusBar.background': '$COLOR',
    'statusBar.foreground': '#ffffff'
}
with open(f, 'w') as out:
    json.dump(settings, out, indent=4)
    out.write('\n')
"
    else
      cat > "$VSCODE_FILE" << VSCEOF
{
    "workbench.colorCustomizations": {
        "titleBar.activeBackground": "$COLOR",
        "titleBar.activeForeground": "#ffffff",
        "statusBar.background": "$COLOR",
        "statusBar.foreground": "#ffffff"
    }
}
VSCEOF
    fi
    echo "  ✓ ${REPO_NAMES[$i]}/.vscode/settings.json"
  done
fi

# --- 4. .code-workspace (multi-repo only) ---
if [ "$REPO_COUNT" -gt 1 ]; then
  python3 -c "
import json
repos = '${REPO_NAMES[*]}'.split()
emoji = '$EMOJI'
color = '$COLOR'
slug = '$SLUG'
folders = [{'path': r, 'name': f'{emoji} {r}'} for r in repos]
workspace = {
    'folders': folders,
    'settings': {
        'workbench.colorCustomizations': {
            'titleBar.activeBackground': color,
            'titleBar.activeForeground': '#ffffff',
            'statusBar.background': color,
            'statusBar.foreground': '#ffffff'
        }
    }
}
with open(f'$WS_PATH/{slug}.code-workspace', 'w') as f:
    json.dump(workspace, f, indent=2)
    f.write('\n')
"
  echo "  ✓ $SLUG.code-workspace"
fi

# --- 5. .env.local per repo (copy from origin + substitute ports) ---
if [ -n "$CONFIG" ] && [ "$REPO_COUNT" -gt 0 ]; then
  python3 << 'PYEOF'
import json, os, shutil

config = json.load(open(os.environ.get('CONFIG', '')))
ws_path = os.environ['WS_PATH']
slot = int(os.environ['SLOT'])
branch = os.environ['BRANCH']
color = os.environ['COLOR']
emoji = os.environ['EMOJI']
slug = branch.replace('/', '-')
port_step = config.get('port_step', 10)
repos = config.get('repos', [])
project_root = os.environ.get('PROJECT_ROOT', '')

# Calculate all ports
repo_ports = {}
origin_ports = {}
for r in repos:
    port = r.get('port_base', 3000) + slot * port_step
    repo_ports[r['name']] = port
    origin_ports[r['name']] = r.get('port_base', 3000)

for r in repos:
    repo_name = r['name']
    repo_path = os.path.join(ws_path, repo_name)
    port = repo_ports[repo_name]

    if not os.path.isdir(repo_path):
        continue

    # Find origin path
    origin = r.get('origin', '.')
    if origin == '.':
        origin_path = project_root
    else:
        origin_path = os.path.normpath(os.path.join(project_root, origin))

    # Copy .env* files from origin and project root
    for search_dir in set([origin_path, project_root]):
        if not search_dir or not os.path.isdir(search_dir):
            continue
        for f in sorted(os.listdir(search_dir)):
            if f.startswith('.env') and 'production' not in f.lower():
                src = os.path.join(search_dir, f)
                dst = os.path.join(repo_path, f)
                if os.path.isfile(src) and not os.path.isfile(dst):
                    shutil.copy2(src, dst)

    # Process .env.local
    env_local = os.path.join(repo_path, '.env.local')
    if not os.path.isfile(env_local):
        existing = ''
    else:
        existing = open(env_local).read()

    # Ensure trailing newline
    if existing and not existing.endswith('\n'):
        existing += '\n'

    # Port substitution: replace origin ports with workspace ports
    for rn, wp in repo_ports.items():
        op = origin_ports.get(rn)
        if op:
            existing = existing.replace(f':{op}', f':{wp}')

    # Workspace variables
    ws_vars = {
        'PORT': str(port),
        'WS_SLOT': str(slot),
        'WS_BRANCH': branch,
        'WS_COLOR': color,
        'WS_EMOJI': emoji,
    }

    # env_template variables
    env_template = r.get('env_template', {})
    for key, val in env_template.items():
        val = str(val)
        val = val.replace('$SLOT', str(slot))
        val = val.replace('$BRANCH', branch)
        val = val.replace('$SLUG', slug)
        val = val.replace('$PORT', str(port))
        val = val.replace('$WORKSPACE_PATH', ws_path)
        for rn, rp in repo_ports.items():
            val = val.replace(f'${rn.upper()}_PORT', str(rp))
        ws_vars[key] = val

    # Apply: replace existing or append
    lines = existing.split('\n')
    existing_keys = set()
    new_lines = []
    for line in lines:
        replaced = False
        for key, val in ws_vars.items():
            if line.startswith(f'{key}='):
                new_lines.append(f'{key}={val}')
                existing_keys.add(key)
                replaced = True
                break
        if not replaced:
            new_lines.append(line)

    for key, val in ws_vars.items():
        if key not in existing_keys:
            new_lines.append(f'{key}={val}')

    with open(env_local, 'w') as f:
        content = '\n'.join(new_lines)
        if not content.endswith('\n'):
            content += '\n'
        f.write(content)

    print(f'  ✓ {repo_name}/.env.local (port {port})')
PYEOF
fi

echo "  ✓ All files generated"
